[theme]
primaryColor = "#4A90E2"  # Color principal
backgroundColor = "#F0F0F0"  # Fondo de la app
secondaryBackgroundColor = "#D6EAF8"  # Fondo de widgets
textColor = "#1C2833"  # Color de texto
font = "sans serif"